### ISSUE TITLE
Adding tree-sitter-gitignore to nvim-treesitter

### ISSUE THREAD

**Issue by andy2mrqz** [shunsambongi/tree-sitter-gitignore#2]
Hello!  Thanks for making this project.

Would you mind if it was referenced/used in nvim-treesitter so it can be more broadly available within the Neovim ecosystem?  Someone there opened [an issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2877) to have a gitignore grammar, and your project came up.

I could do the work of adding it to that project and it would link back to your repo.

Let me know, thanks! 🙂 

PS: Out of curiosity, is this grammar used/referenced in any other projects, or do you just link it to your tooling independently?

**Comment by shunsambongi** [comment]
I'm totally fine with this being added to nvim-treesitter. I was actually planning on contributing this eventually, but I just became a little busy.

And it looks like somebody has already started a PR for this today https://github.com/nvim-treesitter/nvim-treesitter/pull/3303

IIRC somebody added this parser to the helix editor, but I don't use or follow that project, so I'm not sure if it's still being used. Neovim 4 life 😁 

Is there anything else I can help you with before I close this issue?

**Comment by andy2mrqz** [comment]
Thanks for adding your thoughts over there as well!  Yeah once I referenced this repo in the tracking issue for new languages to implement, it got taken away in a PR, which is great! 😁 

Nothing else needed for this issue, thanks for your contributions and collaboration!
